#!/bin/bash
NC='\e[0m'
clear
echo -e "\033[1;96m──────────────────────────────────\033[0m"
echo -e "\033[1;93mUSERNAME          EXP DATE\e[0m"
echo -e "\033[1;96m──────────────────────────────────\033[0m"
while read expired
do
AKUN="$(echo $expired | cut -d: -f1)"
ID="$(echo $expired | grep -v nobody | cut -d: -f3)"
exp="$(chage -l $AKUN | grep "Account expires" | awk -F": " '{print $2}')"
status="$(passwd -S $AKUN | awk '{print $2}' )"
if [[ $ID -ge 1000 ]]; then
if [[ "$status" = "L" ]]; then
printf "%-17s %2s %-17s %2s \n" "$AKUN" "$exp     " "LOCKED" 
else
printf "%-17s %2s %-17s %2s \n" "$AKUN" "$exp     " 
fi
fi
done < /etc/passwd
JUMLAH="$(awk -F: '$3 >= 1000 && $1 != "nobody" {print $1}' /etc/passwd | wc -l)"
echo -e "\033[1;96m──────────────────────────────────\033[0m"
echo -e "\033[1;97mTOTAL OVPN ACCOUNT :    $JUMLAH USER   \e[0m"
echo -e "\033[1;96m──────────────────────────────────\033[0m"
read -p " Username : " USERSSH

if [ -z $USERSSH ]; then
    echo -e "Username cannot be empty "
else
    if getent passwd $USERSSH >/dev/null 2>&1; then
        userdel $USERSSH >/dev/null 2>&1
        sed -i "/^### $user/d" /etc/ssh/.ssh.db
        sed -i "/^#ssh# $USERSSH/d" /etc/ssh/.ssh.db
echo -e "                   User $USERSSH was removed."
    else
        echo -e "Failure: User $USERSSH Not Exist."
    fi
fi
    clear
echo -e "\033[1;96m──────────────────────────────────\033[0m"
echo -e "\033[1;97m        DELETE SSH ACCOUNT           \E[0m"
echo -e "\033[1;96m──────────────────────────────────\033[0m" 
echo -e "\033[1;97mClient Name : $USERSSH ${NC} "
echo -e "\033[1;97mExfired On  : $exp ${NC}"
echo -e "\033[1;96m──────────────────────────────────\033[0m"
echo -e ""
read -n 1 -s -r -p "Press [ Enter ] to back on menu"
menu
