#!/bin/bash
clear
logfile="/etc/openvpn/server/udpclient.log"


if [ ! -f "$logfile" ]; then
    echo "Log file does not exist."
    exit 1
fi


output=$(awk -F, '/OpenVPN CLIENT LIST/{p=1; next} p && /ROUTING TABLE/{p=0} p && !/OpenVPN CLIENT LIST|ROUTING TABLE/{if ($1 != "Common Name" && $1 != "Updated" && $1 != "UNDEF") print $1}' "$logfile" | sort | uniq -c)

if [ -z "$output" ]; then
    echo -e "\033[1;96m──────────────────────────────────\033[0m"
    echo -e "\033[1;97m           USERS ONLINE           \E[0m"
    echo -e "\033[1;96m──────────────────────────────────\033[0m"
    echo -e "\033[1;91mNo users connected.\033[0m"
echo -e "\033[1;96m──────────────────────────────────\033[0m"
echo -e "\033[1;97m         SCRIPT BY ILYASS\033[0m"
echo -e "\033[1;96m──────────────────────────────────\033[0m"
read -n 1 -s -r -p "Press [ Enter ] to back on menu"
menu

fi

echo -e "\033[1;96m──────────────────────────────────\033[0m"
echo -e "\033[1;97m           USERS ONLINE           \E[0m"
echo -e "\033[1;96m──────────────────────────────────\033[0m"
while read -r line; do
    count=$(echo "$line" | awk '{print $1}')
    user=$(echo "$line" | awk '{print $2}')
    if [ "$user" == "UNDEF" ]; then
        user="Undefined"
    fi
    printf "\033[1;93m[%-3s] \033[0m\033[1;32m%-20s\033[0m\n" "$count" "$user"
done <<< "$output"
echo -e "\033[1;96m──────────────────────────────────\033[0m"
echo -e "\033[1;97m         SCRIPT BY ILYASS\033[0m"
echo -e "\033[1;96m──────────────────────────────────\033[0m"
read -n 1 -s -r -p "Press [ Enter ] to back on menu"
menu
